kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta2
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
        enable-admission-plugins: MutatingAdmissionWebhook
