apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base.yaml
patchesJSON6902:
- target:
    group: admissionregistration.k8s.io 
    version: v1
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-config 
  path: cabundle-patch.yaml
